spring:
  application:
    name: RegistrationService
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      uri: mongodb+srv://${DB_USERNAME}:${DB_PASSWORD}@cluster0.ysz3f.mongodb.net/imst_dev?retryWrites=true
